spring:
  application:
    name: bus-ticket-system-demo

  datasource:
    url: jdbc:mysql://localhost:3306/bus_ticket_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 143323
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

sa-token:
  token-name: satoken
  timeout: 2592000
  is-share: false
  token-style: uuid

pagehelper:
  helperDialect: mysql
  reasonable: true

